### ISSUE TITLE
Error: /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:2:in `<class:Thor>': superclass mismatch for class Command (TypeError)

### ISSUE THREAD

**Issue by Intelligent2013** [glossarist/iev-document#1]
Source: https://github.com/metanorma/mn-native-pdf/issues/118#issuecomment-885664237

I'm trying to generate xml file (OS: Ubuntu, the command `make all`) for this repo and the process ends with the error:
```
[relaton] Info: detecting backends:
Traceback (most recent call last):
	47: from /usr/local/bin/metanorma:23:in `<main>'
	46: from /usr/local/bin/metanorma:23:in `load'
	45: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/exe/metanorma:35:in `<top (required)>'
	44: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/exe/metanorma:22:in `block in <top (required)>'
	43: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli.rb:34:in `start'
	42: from /usr/lib/ruby/vendor_ruby/thor/base.rb:444:in `start'
	41: from /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
	40: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	39: from /var/lib/gems/2.7.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
	38: from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	37: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/command.rb:45:in `compile'
	36: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/command.rb:45:in `each'
	35: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/command.rb:45:in `block in compile'
	34: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/command.rb:210:in `compile_document'
	33: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/compiler.rb:35:in `compile'
	32: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/compiler.rb:30:in `compile'
	31: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	30: from /var/lib/gems/2.7.0/gems/metanorma-1.3.7/lib/metanorma/compile.rb:27:in `compile'
	29: from /var/lib/gems/2.7.0/gems/metanorma-1.3.7/lib/metanorma/compile.rb:96:in `process_input'
	28: from /var/lib/gems/2.7.0/gems/metanorma-1.3.7/lib/metanorma/processor.rb:24:in `input_to_isodoc'
	27: from /var/lib/gems/2.7.0/gems/metanorma-1.3.7/lib/metanorma/input/asciidoc.rb:18:in `process'
	26: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/convert.rb:119:in `convert'
	25: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/document.rb:944:in `convert'
	24: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/asciidoctor/standoc/utils.rb:13:in `convert'
	23: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/asciidoctor/standoc/base.rb:163:in `document'
	22: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/asciidoctor/standoc/base.rb:197:in `makexml'
	21: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/asciidoctor/standoc/base.rb:189:in `makexml1'
	20: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/asciidoctor/standoc/base.rb:171:in `version'
	19: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:16:in `versioned'
	18: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `all_modules'
	17: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `flat_map'
	16: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `each'
	15: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `block in all_modules'
	14: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `all_modules'
	13: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `flat_map'
	12: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `each'
	11: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `block in all_modules'
	10: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:10:in `all_modules'
	 9: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:10:in `map'
	 8: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:10:in `block in all_modules'
	 7: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:10:in `const_get'
	 6: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:10:in `require'
	 5: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:1:in `<top (required)>'
	 4: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:1:in `require_relative'
	 3: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:1:in `<top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:1:in `require_relative'
	 1: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:1:in `<top (required)>'
/var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:2:in `<class:Thor>': superclass mismatch for class Command (TypeError)
make[1]: *** [Makefile:88: sources/iec-60050-192.xml] Error 1
rm sources/data/concept-1921204.adoc sources/data/concept-1920926.adoc sources/data/concept-1920412.adoc ...
...
make[1]: Leaving directory '/home/intluser/iev-document'
make: *** [Makefile:61: all] Error 2
```

**Comment by ronaldtse** [comment]
Believe this is fixed. Closing.
